---
title: "R Notebook"
output: html_notebook
---

```{r}
#install packages
install.packages ("tidyverse")
```


```{r}
#load libraries
library(tidyverse)
```


```{r}
#set working directory (adjust this for your own computer)
setwd("C:/Users/muhir/Downloads/Data Science for Businesses")
```


```{r}
#read dataset into R
creditdf <- read.csv("Credit.csv")
View(creditdf)

```

```{r}
#Convert categorical variables to factors with levels and labels
creditdf$Student <- factor(creditdf$Student,levels = c(0,1),labels = c("No","Yes"))
creditdf$Gender <- factor(creditdf$Gender,levels = c(0,1),labels = c("Male","Female"))
creditdf$Married <- factor(creditdf$Married,levels = c(0,1),labels = c("No","Yes"))

```

```{r}
#check for missing data
sum(is.na(creditdf))
```


```{r}
#generate summary statistics for all variables in dataframe
summary(creditdf)
```
```{r}
#partition the data into a training set and a validation set
#set seed so the random sample is reproducible
set.seed(42)
sample <- sample(c(TRUE, FALSE), nrow(creditdf), replace=TRUE, prob=c(0.5,0.5))
traincred  <- creditdf[sample, ]
validatecred <- creditdf[!sample, ]
```

```{r}
#create a correlation matrix with all quantitative variables in the data frame
cor(creditdf[c(1, 2, 3, 4, 5, 9)])
```
```{r}
#run a multiple regression model using the "train" dataframe and all 
#available independent variables
traincred_reg <- lm(Balance ~ Income + Limit + Rating + Age + Education + 
                           Student + Gender + Married, data = traincred)

summary(traincred_reg)
```
```{r}
#install packages
#install.packages ("car")

#load libraries
library(car)
```
```{r}
#calculate Variance Inflation Factor for each variable to assess 
#multicollinearity
vif(traincred_reg)

```
```{r}
#run a multiple regression model using the "train" dataframe and all 
#available independent variables
traincred_reg2 <- lm(Balance ~ Income + Rating + Age + Education + 
                           Student + Gender + Married, data = traincred)

summary(traincred_reg2)
```
```{r}
#Create a vector of predicted values generated from the multiple 
#regression above
credit_pred = predict(traincred_reg2)

#Create a vector of residuals generated from the multiple regression above
credit_res = resid(traincred_reg2)
```


```{r}
#Create a data frame of the predicted values and the residuals
pred_res_df <- data.frame(credit_pred, credit_res)

#create a scatterplot of the residuals versus the predicted values
ggplot(data = pred_res_df, mapping = aes(x = credit_pred, y = credit_res)) +
  geom_point() +
  labs(title = "Plot of residuals vs. predicted values", x = "Predicted values",
       y = "Residuals")
```


```{r}
#create a vector of standardized residuals generated from the multiple
#regression above
credit_std.res = rstandard(traincred_reg2)

#produce normal scores for the standardized residuals and create
#normal probability plot
qqnorm(credit_std.res, ylab = "Standardized residuals", xlab = "Normal scores")

```
```{r}
#run a multiple regression model using the "train" dataframe and significant 
#independent variables
traincred_reg3 <- lm(Balance ~ Income + Rating + Age + Student, data = traincred)

summary(traincred_reg3)
```
```{r}
#run a multiple regression model using the "train" dataframe and all 
#available independent variables
validcred_reg <- lm(Balance ~ Income + Rating + Age + Student, data = validatecred)

summary(validcred_reg)
```
```{r}
#read inventory dataset into R
credt_preddf <- read.csv("credit_card_prediction.csv")
View(credt_preddf)
```


```{r}
#Convert categorical variables to factors with levels and labels
credt_preddf$Student <- factor(credt_preddf$Student,levels = c(0,1),labels = c("No","Yes"))

```


```{r}
#estimate predicted y values and prediction intervals for credit card balances for three new cardholders 

predict(validcred_reg, credt_preddf, interval = "prediction", level = 0.95)

```

