---
title: "R Notebook"
output: html_notebook
---

```{r}
#install packages
#install.packages ("tidyverse")
#install.packages("caret")
#install.packages("ROCR")
#install.packages("ROSE")
```


```{r}
#load libraries
library(tidyverse)
library(caret)
library(ROCR)
library(ROSE)
```


```{r}
#set working directory (adjust this for your own computer)
setwd("C:/Users/muhir/Downloads/Data Science for Businesses")
```


```{r}
#read dataset into R
insurancedf <- read.csv("insurance.csv")
View(insurancedf)
```


```{r}
#Convert categorical variables to factors with levels and labels
insurancedf$CLAIM<-factor(insurancedf$CLAIM,levels = c(0,1),labels = c("No","Yes"))
insurancedf$KIDSDRIV<-factor(insurancedf$KIDSDRIV,levels = c(0,1),labels = c("No","Yes"))
insurancedf$HOMEKIDS<-factor(insurancedf$HOMEKIDS,levels = c(0,1),labels = c("No","Yes"))
insurancedf$HOMEOWN<-factor(insurancedf$HOMEOWN,levels = c(0,1),labels = c("No","Yes"))
insurancedf$MSTATUS<-factor(insurancedf$MSTATUS,levels = c(0,1),labels = c("No","Yes"))
insurancedf$GENDER<-factor(insurancedf$GENDER,levels = c(0,1),labels = c("Male","Female"))
insurancedf$EDUCATION<-factor(insurancedf$EDUCATION,levels = c(0,1),labels = c("High School only","College or beyond"))
insurancedf$CAR_USE<-factor(insurancedf$CAR_USE,levels = c(0,1),labels = c("Private","Commercial"))
insurancedf$RED_CAR<-factor(insurancedf$RED_CAR,levels = c(0,1),labels = c("No","Yes"))
insurancedf$CLM_BEF<-factor(insurancedf$CLM_BEF,levels = c(0,1),labels = c("No","Yes"))
insurancedf$REVOKED<-factor(insurancedf$REVOKED,levels = c(0,1),labels = c("No","Yes"))
insurancedf$MVR_PTS<-factor(insurancedf$MVR_PTS,levels = c(0,1),labels = c("No","Yes"))
insurancedf$URBANICITY<-factor(insurancedf$URBANICITY,levels = c(0,1),labels = c("Rural","Urban"))
```


```{r}
#check for missing data
sum(is.na(insurancedf))
```


```{r}
#generate summary statistics for all variables in dataframe
summary(insurancedf)
```


```{r}
#set seed so the random sample is reproducible
set.seed(42)

#Partition the Optiva dataset into a training, validation and test set
Samples<-sample(seq(1,3),size=nrow(insurancedf),replace=TRUE,prob=c(0.6,0.2,0.2))
Train<-insurancedf[Samples==1,]
Validate<-insurancedf[Samples==2,]
Test<-insurancedf[Samples==3,]
```


```{r}
#View descriptive statistics for each dataframe
summary(Train)
summary(Validate)
summary(Test)


```

```{r}
options(scipen=999)
lrinsurance <- glm(CLAIM ~ ., data = Train, 
               family = binomial(link = "logit"))
```


```{r}
# model summary
summary(lrinsurance)

```
```{r}
# obtain probability of defaulting for each observation in validation set
lrprobsO <- predict(lrinsurance, newdata = Validate, type = "response")
```


```{r}
#Attach probability scores to Validate dataframe
Validate <- cbind(Validate, Probabilities=lrprobsO)
```


```{r}
# obtain predicted class for each observation in validation set using threshold of 0.5
lrclassO <- as.factor(ifelse(lrprobsO > 0.5, "Yes","No"))
```


```{r}
#Attach predicted class to Validate dataframe
Validate <- cbind(Validate, PredClass=lrclassO)
```


```{r}
#Create a confusion matrix using "Yes" as the positive class 
confusionMatrix(lrclassO, Validate$CLAIM, positive = "Yes" )

```
```{r}
#create a prediction object to use for the ROC Curve
predROC <- prediction(lrprobsO, Validate$CLAIM)
```


```{r}
#create a performance object to use for the ROC Curve
perfROC <- performance(predROC,"tpr", "fpr")
```


```{r}
#plot the ROC Curve
plot(perfROC)
abline(a=0, b= 1)
```


```{r}
# compute AUC 
performance(predROC, measure="auc")@y.values[[1]]

```
```{r}
#Create a data frame with only the predictor variables by removing 
#column 2 (Loan Default)
xsdf<-Train[c(-1)]
View(xsdf)
```


```{r}
#Create an oversampled training subset
set.seed(42)
oversample<-upSample(x=xsdf, y=Train$CLAIM, yname = "CLAIM")

table(oversample$CLAIM)
```


```{r}
# fit logistic regression model on the CLAIM outcome variable
# using specified input variables with the oversample dataframe
lrOver <- glm(CLAIM ~ ., data = oversample, 
              family = binomial(link = "logit"))
```


```{r}
# model summary
summary(lrOver)
```
```{r}
#First using logistic regression model built on oversampled training subset

# obtain probability of defaulting for each observation in validation set
lrprobsO <- predict(lrOver, newdata = Validate, type = "response")

# obtain predicted class for each observation in validation set using threshold of 0.5
lrclassO <- as.factor(ifelse(lrprobsO > 0.5, "Yes","No"))

#Create a confusion matrix using "Yes" as the positive class 
confusionMatrix(lrclassO, Validate$CLAIM, positive = "Yes" )
```
```{r}
#Plot ROC Curve for model from oversampled training set

#create a prediction object to use for the ROC Curve
predROCO <- prediction(lrprobsO, Validate$CLAIM)

#create a performance object to use for the ROC Curve
perfROCO <- performance(predROCO,"tpr", "fpr")

#plot the ROC Curve
plot(perfROCO)
abline(a=0, b= 1)
```


```{r}
# compute AUC 
performance(predROCO, measure="auc")@y.values[[1]]
```
```{r}
# obtain probability of defaulting for each observation in Train set
lrprobsO_Test <- predict(lrOver, newdata = Train, type = "response")

# obtain predicted class for each observation in validation set using threshold of 0.5
lrclassO_Test <- as.factor(ifelse(lrprobsO_Test > 0.5, "Yes","No"))

#Create a confusion matrix using "Yes" as the positive class 
confusionMatrix(lrclassO_Test, Train$CLAIM, positive = "Yes" )
```
```{r}
#create a prediction object to use for the ROC Curve
predROCO_Test <- prediction(lrprobsO_Test, Train$CLAIM)

#create a performance object to use for the ROC Curve
perfROCO_Test <- performance(predROCO_Test,"tpr", "fpr")

#plot the ROC Curve
plot(perfROCO_Test)
abline(a=0, b= 1)
```

```{r}
# compute AUC 
performance(predROCO_Test, measure="auc")@y.values[[1]]
```
```{r}
#read new dataset into R
insurance_pred <- read.csv("insurance_predictions.csv")
View(insurance_pred)
```


```{r}
#Convert categorical variables to factors with levels and labels
#Convert categorical variables to factors with levels and labels
insurance_pred$CLAIM<-factor(insurance_pred$CLAIM,levels = c(0,1),labels = c("No","Yes"))
insurance_pred$KIDSDRIV<-factor(insurance_pred$KIDSDRIV,levels = c(0,1),labels = c("No","Yes"))
insurance_pred$HOMEKIDS<-factor(insurance_pred$HOMEKIDS,levels = c(0,1),labels = c("No","Yes"))
insurance_pred$HOMEOWN<-factor(insurance_pred$HOMEOWN,levels = c(0,1),labels = c("No","Yes"))
insurance_pred$MSTATUS<-factor(insurance_pred$MSTATUS,levels = c(0,1),labels = c("No","Yes"))
insurance_pred$GENDER<-factor(insurance_pred$GENDER,levels = c(0,1),labels = c("Male","Female"))
insurance_pred$EDUCATION<-factor(insurance_pred$EDUCATION,levels = c(0,1),labels = c("High School only","College or beyond"))
insurance_pred$CAR_USE<-factor(insurance_pred$CAR_USE,levels = c(0,1),labels = c("Private","Commercial"))
insurance_pred$RED_CAR<-factor(insurance_pred$RED_CAR,levels = c(0,1),labels = c("No","Yes"))
insurance_pred$CLM_BEF<-factor(insurance_pred$CLM_BEF,levels = c(0,1),labels = c("No","Yes"))
insurance_pred$REVOKED<-factor(insurance_pred$REVOKED,levels = c(0,1),labels = c("No","Yes"))
insurance_pred$MVR_PTS<-factor(insurance_pred$MVR_PTS,levels = c(0,1),labels = c("No","Yes"))
insurance_pred$URBANICITY<-factor(insurance_pred$URBANICITY,levels = c(0,1),labels = c("Rural","Urban"))
```


```{r}
# make predictions for new data (for which loan default is unknown)
lrprobs_insurance_pred <- predict(lrOver, newdata = insurance_pred , type = "response")
```


```{r}
#Attach probability scores to new_customers dataframe 
insurance_pred <- cbind(insurance_pred, Probabilities=lrprobs_insurance_pred)
View(insurance_pred)
```

